### ISSUE TITLE
Help with TTL Convertor

### ISSUE THREAD

**Issue by thejman1989** [peca2345/ESPHome-modbus-heatpump-Gree-Versati-III#1]
Thanks for writing the great tutorial. This was exactly what I needed. I have one question though. I have bought a TTL converter but compared to your convertor it's missing one output. This is the one I have. 

![image](https://user-images.githubusercontent.com/3214644/224415593-d337b96c-5240-4d7d-ae7f-0646f3003d1d.png)

So by exlusion this seems to the "DE/RG" ports on your version. Is that correct? 

![image](https://user-images.githubusercontent.com/3214644/224415767-86305ea3-c46c-4700-a2f2-217a853ff096.png)

Im quite new to the whole modbus interface / ESPHome, so was hoping you could confirm that this is the right one.

**Comment by peca2345** [comment]
Hello, I have this converter also but I couldn't get it to work without flow pin DE+RE..

these converters cost 1 USD, so I would recommend to buy the same..

**Comment by peca2345** [comment]
I think the pin you marked is GND...

**Comment by thejman1989** [comment]
Thanks, i will order the same one and try again. The pin on the bottom left is GND, or do you mean it has 2 GND pins?

**Comment by peca2345** [comment]
Your converter has two separate GNDs.. one for the ESP and the other for the modbus device
