### ISSUE TITLE
Need convert for negative temperature.

### ISSUE THREAD

**Issue by straga** [peca2345/ESPHome-modbus-heatpump-Gree-Versati-III#3]
- platform: modbus_controller
    modbus_controller_id: versati3
    name: "versati_118_outdoor_temp"
    address: 118
    unit_of_measurement: "°C" 
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - lambda: |-
        if (x > 32767) {
          x -= 65536;
        }
        return x * 0.1;

**Comment by peca2345** [comment]
- platform: modbus_controller
    modbus_controller_id: versati3
    name: "versati_118_outdoor_temp"
    address: 118
    unit_of_measurement: "°C" 
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

**Comment by peca2345** [comment]
fixed... changed U_WORD to S_WORD for all sensors
